### ISSUE TITLE
make bundle postgresql support replicatation mode

### ISSUE THREAD

**Issue by NiuBlibing** [risingwavelabs/helm-charts#140]
The bundle postgresql chart is outdate which will failed when use replication mode.
https://github.com/bitnami/charts/pull/30720

**Comment by arkbriar** [comment]
Thanks for the issue. Let me take a look.

**Comment by NiuBlibing** [comment]
![image](https://github.com/user-attachments/assets/abad75b2-4313-436a-becc-dcd972872599)
Seems that `PG_HOST` needs to modify to support replication mode of postgresql.

**Comment by NiuBlibing** [comment]
> @NiuBlibing can you share the values you've tried? I'll take a look afterwards.

```yaml
tags:
  postgresql: true

postgresql:
  global:
    defaultStorageClass: "open-local-lvm"

  architecture: replication
  replication:
    synchronousCommit: "remote_apply"
    numSynchronousReplicas: 1
    applicationName: qifusec_risingwave

  auth:
    postgresPassword: "risingwave_test"
    database: "risingwave"

  primary:
    resourcesPreset: "large"
    persistence:
      enabled: true
      size: 32Gi
    persistentVolumeClaimRetentionPolicy:
      enabled: true
      whenScaled: Retain
      whenDeleted: Delete
    service:
      ports:
        postgresql: 5432

  readReplicas:
    resourcesPreset: "large"
    persistence:
      enabled: true
      size: 32Gi
    persistentVolumeClaimRetentionPolicy:
      enabled: true
      whenScaled: Retain
      whenDeleted: Delete

  metrics:
    enabled: true

```
