### ISSUE TITLE
Bug: pre-stop hook appears when `autoDeregistration` is turned off

### ISSUE THREAD

**Issue by arkbriar** [risingwavelabs/helm-charts#176]
The pre-stop hook is added unexpectedly when `embeddedServing` set to `true` and `autoDeregistration` set to false.

```yaml
        lifecycle:
          preStop:
            exec:
              command:
              - bash
              - -c
              - |-
                /risingwave/bin/risingwave ctl meta unregister-workers --yes \
                  --workers ${POD_IP}:5688
```
