### ISSUE TITLE
serviceAccount annotations are rendered as labels

### ISSUE THREAD

**Issue by Babbleshack** [risingwavelabs/helm-charts#2]
When configuring serviceAccount for state store on s3 on eks infrastructure, if `serviceAccount.create` is true a annotation is used to associate the serviceAccount in eks with aws IAM role for accessing the state store bucket.

However the current helm chart renders the annotations as a label. This makes the serviceAccount resource manifest generated by helm invalid.
 
For example a rendered manifest will look like:

```yaml
# Source: risingwave/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: risingwave
  labels:
    helm.sh/chart: risingwave-0.1.21
    app.kubernetes.io/name: risingwave
    app.kubernetes.io/instance: risingwave
    app.kubernetes.io/version: "v1.2.0"
    app.kubernetes.io/managed-by: Helm
    eks.amazonaws.com/role-arn: arn:aws:iam::1234567890123:role/s3/some-role
```
notice the ` eks.amazonaws.com/role-arn` key should be a annotation and not a label.

This happens because the template has the following content

```yaml
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "risingwave.serviceAccountName" . }}
  labels:
    {{- include "risingwave.labels" . | nindent 4 }}
  {{- $annotations := (include "risingwave.annotations" . ) | trim }}
  {{- if $annotations }}
  annotations:
    {{ nindent 4 $annotations }}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
```

The problem is that the .Values.serviceAccount.annotations is being rendered directly under the metadata.labels section instead of the metadata.annotations section due to how the templating has been written.

Instead the template should be:

```yaml
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "risingwave.serviceAccountName" . }}
  labels:
    {{- include "risingwave.labels" . | nindent 4 }}
  {{- $annotations := (include "risingwave.annotations" . ) | trim }}
  annotations:
    {{- if $annotations }}
    {{- nindent 4 $annotations }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}

```

this will then render as:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: risingwave
  labels:
    helm.sh/chart: risingwave-0.1.22
    app.kubernetes.io/name: risingwave
    app.kubernetes.io/instance: risingwave
    app.kubernetes.io/version: "v1.2.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::1234567890123:role/s3/some-role
```
